disasterMangement/disasterMangement/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    #path('website/',include('django.contrib.auth.urls')),
    path('website/',include("website.urls")),
    path('admin/', admin.site.urls),
]

disasterMangement/website/urls.py
from django.urls import path
from . import views

app_name = "dm"
urlpatterns = [
    path('', views.home, name="home"),
    path('gen_guidelines/', views.gen_guidelines, name="gen_guidelines"),
    path('login/', views.signin, name="signin"),
    path('signup/', views.signup, name="signup"),
    path('signup/volunteer', views.signup_volunteer, name="signup_vol"),
    path('signup/organization', views.signup_org, name="signup_org"),
    path('logout/', views.logout_user, name="logout"),
]

disasterMangement/website/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class myUser(AbstractUser):
    Admin = '1'
    Volunteer = '2'
    Organization = '3'
    
    Email_To_User_Map = {
        "admin": Admin,
        "com": Volunteer,
        "org": Organization
    }
    User_Type = ((Admin,"Admin"),(Volunteer,"Volunteer"),(Organization,"Organization"))
    user_role = models.CharField(max_length=20, choices=User_Type)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.user_role == "2":
            Volunteer.objects.get_or_create(role=self)
        elif self.user_role == "3":
            Organization.objects.get_or_create(role=self)
        elif self.user_role == "1":
            Admin.objects.get_or_create(role=self)


class Admin(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    email = models.EmailField()

class Volunteer(models.Model):
    role = models.OneToOneField(myUser, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    age = models.IntegerField()
    nationality = models.CharField(max_length=25)
    email = models.EmailField()

class Organization(models.Model):
    Org_type = (("PRIVATE","private"),("GOVT.","government"),("SEMI GOVT.","semi_govt"))
    role = models.OneToOneField(myUser, on_delete=models.CASCADE)
    org_name = models.CharField(max_length=30)
    org_type = models.CharField(max_length=20, choices=Org_type, blank=False)
    org_email = models.EmailField()
    

disasterMangement/website/forms.py
from django.forms import forms
from .models import myUser, Volunteer, Organization
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms

class Signin_Form(AuthenticationForm):
    class Meta:
        model = myUser
        fields = ['username','password']

        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control'}),
            'password': forms.PasswordInput(attrs={'class':'form-control'}),
        }

############################################ Sign up forms ##############################
class Signup_Volunteer(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    age = forms.IntegerField()
    nationality = forms.CharField(max_length=30)

    class Meta:
        model = myUser
        fields = ['username', 'password1', 'password2']

        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control'}),
            'first_name': forms.TextInput(attrs={'class':'form-control'}),
            'last_name': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.TextInput(attrs={'class':'form-control'}),
            'age': forms.NumberInput(attrs={'class':'form-control'}),
            'nationality': forms.TextInput(attrs={'class':'form-control'}),
            'password1': forms.PasswordInput(attrs={'class':'form-control'}),
            'password2': forms.PasswordInput(attrs={'class':'form-control'}),
        }

class Signup_Org(UserCreationForm):
    org_name = forms.CharField(max_length=30)
    org_type = forms.ChoiceField(choices=Organization.Org_type)
    org_email = forms.EmailField()

    class Meta:
        model = myUser
        fields = ['username', 'password1', 'password2']

        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control'}),
            'org_email': forms.TextInput(attrs={'class':'form-control'}),
            'org_name': forms.TextInput(attrs={'class':'form-control'}),
            'org_type': forms.Select(attrs={'class':'form-control'}),
            'password1': forms.PasswordInput(attrs={'class':'form-control'}),
            'password2': forms.PasswordInput(attrs={'class':'form-control'}),
        }

disasterMangement/website/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from .forms import Signup_Org,Signup_Volunteer,Signin_Form
from .models import myUser, Volunteer, Organization, Admin

# Create your views here.
def home(request):
    return render(request, 'home.html',{})

def gen_guidelines(request):
    return render(request, 'gen_guidelines.html')


################################# LOGIN Views ##############################
# def signin(request):
#     if request.method == "POST":
#         userType = request.POST['userType']
#         if userType == 'volunteer':
#             return render(request, 'signin_vol.html')
#         else:
#             return render(request, 'signin_org.html')
        
#     return render(request, 'signin.html')

def signin(request):
    form = Signin_Form()
    if request.method == "POST":
        form = Signin_Form(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username = username, password = password)
            if user is not None:
                login(request, user)
                messages.info(request,"You have logged in successfully!!")
                return redirect('dm:home')
            else:
                messages.info(request,"Invalid Credentials")
                return redirect('dm:signin')
        
        else:
            messages.error(request, "Form invalid")
            print(form.errors)
            return redirect('dm:signin')
        
    return render(request, 'signin.html', {
        "form":form
        })

# def signin_org(request):
#     form = Signin_Form()
#     if request.method == "POST":
#         form = Signin_Form(request.POST)
#         username = form.cleaned_data["username"]
#         password = form.cleaned_data["password"]
#         user = authenticate(request, username = username, password = password)
#         if user is not None:
#             if user.user_type == myUser.Volunteer:
#                 login(request, user)
#                 messages.info(request,"You have logged in successfully!!")
#                 return redirect('dm:home')
#             else:
#                 messages.error(request,"You are not an organizatoin. Redirecting to volunteer login page...")
#                 return redirect('signin_vol')                
#         else:
#             messages.info(request,"Invalid Credentials")
#             return redirect('dm:signin')

#     return render(request, 'signin_org.html', {
#         "form":form
#     })

def logout_user(request):
    logout(request)
    messages.info(request,"You have logged out!!")
    return redirect('dm:home')


################################# REGISTER Views ##############################
def signup(request):
    if request.method == "POST":
        type = request.POST['userType']
        if type == 'volunteer':
            return render(request, 'signup_vol.html')
        else:
            return render(request, 'signup_org.html')
        
    return render(request, 'signup.html')

  
def signup_volunteer(request):
    form = Signup_Volunteer()
    if request.method == 'POST':
        form = Signup_Volunteer(request.POST)
        
        if form.is_valid():
            username = form.cleaned_data["username"]
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            email = form.cleaned_data["email"]
            age = form.cleaned_data["age"]
            nationality = form.cleaned_data["nationality"]
            password1 = form.cleaned_data["password1"]
            password2 = form.cleaned_data["password2"]

            username_exists = myUser.objects.filter(username=username).exists()
            if username_exists:
                messages.error(request, 'User with this username already exists. Please try another username!!')
                return redirect('dm:signup_vol')
            
            if password1 != password2:
                messages.error(request,"Provided passwords don't match")
                return redirect('dm:signup_vol')
            
            user_type = email.split('@')[1].split('.')[1]
            if user_type not in myUser.Email_To_User_Map:
                messages.error(request, "The provided email id seems invalid")
                return redirect('dm:signup_vol')

            email_exists = Volunteer.objects.filter(email=email).exists()
            if email_exists:
                messages.error(request, 'User with this email id already exists. Please proceed to login!!')
                return redirect('dm:signin_vol')
            
            user = myUser(username=username)
            user.set_password(password1)
            user.user_role = myUser.Volunteer
            user.save()

            volunteer = Volunteer(role=user.user_role, first_name=first_name, last_name=last_name, age=age, nationality=nationality, email=email)
            volunteer.save()
            return redirect('dm:signin_vol')
        
        else:
            messages.error(request,"Please...fill all the details")
            print(form.errors)
            return redirect('dm:signup_vol')
    
    return render(request, 'signup_vol.html',{
        "form":form
    })


def signup_org(request):
    if request.method == 'POST':
        form = Signup_Org(request.POST)
        
        if form.is_valid():
            username = form.cleaned_data["username"]
            org_name = form.cleaned_data["org_name"]
            org_type = form.cleaned_data["org_type"]
            org_email = form.cleaned_data["org_email"]
            password1 = form.cleaned_data["password1"]
            password2 = form.cleaned_data["password2"]

            username_exists = myUser.objects.filter(username=username).exists()
            if username_exists:
                messages.error(request, 'User with this username already exists. Please try another username!!')
                return redirect('dm:signup_org')
            
            if password1 != password2:
                messages.error(request,"Provided passwords don't match")
                return redirect('dm:signup_org')
            
            user_type = org_email.split('@')[1].split('.')[1]
            if user_type not in myUser.Email_To_User_Map:
                messages.error(request, "The provided email id seems invalid")
                return redirect('dm:signup_org')

            email_exists = Volunteer.objects.filter(email=org_email).exists()
            if email_exists:
                messages.error(request, 'User with this email id already exists. Please proceed to login!!')
                return redirect('dm:signin_org')
            
            user = myUser(username=username)
            user.set_password(password1)
            user.user_role = myUser.Organization
            user.save()

            org = Organization(role=user.user_role, org_name=org_name, org_type=org_type, org_email=org_email)
            org.save()
            return redirect('dm:signin_org')
        
        else:
            messages.error(request,"Please...fill all the details")
            return redirect('dm:signup_org')
    
    else:
        form = Signup_Org()
    
    return render(request, 'signup_org.html', {"form": form})

disasterMangement/website/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    {% include 'navbar.html' %}

  

    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
  </body>
</html>

disasterMangement/website/templates/gen_guidelines.html
{% extends 'base.html' %}

{% block title %} General Guidlines {% endblock %}

{% block content %}

<div class="container">
    <h1 class="text-center my-4">Disaster Safety Measures</h1>
    <div class="list-group">
        <div class="list-group-item">
            <h4 class="list-group-item-heading">1. Prevention</h4>
            <p class="list-group-item-text">This involves taking proactive measures to prevent the occurrence of disasters. This could include proper urban planning, adherence to safety codes, and environmental conservation.</p>
        </div>
        <div class="list-group-item">
            <h4 class="list-group-item-heading">2. Mitigation</h4>
            <p class="list-group-item-text">This involves reducing the risk of any disaster or its severity or consequences. This could involve building flood barriers, earthquake-resistant structures, and implementing fire safety measures.</p>
        </div>
        <div class="list-group-item">
            <h4 class="list-group-item-heading">3. Capacity Building</h4>
            <p class="list-group-item-text">This includes research and knowledge management to understand disasters better and develop effective strategies to deal with them.</p>
        </div>
        <div class="list-group-item">
            <h4 class="list-group-item-heading">4. Preparedness</h4>
            <p class="list-group-item-text">This involves being ready to deal with any disaster. This could include having evacuation plans in place, training emergency response teams, and educating the public about what to do in a disaster.</p>
        </div>
        <div class="list-group-item">
            <h4 class="list-group-item-heading">5. Response</h4>
            <p class="list-group-item-text">This involves taking immediate action when a disaster occurs. This could include rescue operations, providing immediate medical care, and ensuring the provision of food, water, and shelter.</p>
        </div>
        <div class="list-group-item">
            <h4 class="list-group-item-heading">6. Rehabilitation and Reconstruction</h4>
            <p class="list-group-item-text">After a disaster, it's important to help affected people return to normal life and to rebuild damaged infrastructure.</p>
        </div>
    </div>
    <p class="my-4">In addition to these, specific guidelines exist for different types of disasters such as earthquakes, floods, cyclones, etc. It's important to be aware of the guidelines relevant to the disasters common in your area.</p>
</div>

{%endblock%}

disasterMangement/website/templates/home.html
{% extends 'base.html' %}
{%load static%}

{% block title %} Page Title {% endblock %}

{% block content %}

<!-- Showcase -->
<section class="bg-dark text-light p-5 text-centre">
    <div class="container">
        <div class="d-sm-flex">
            <div>
                <h1>Help those in need!!</h1>
            </div>
            <img class="image-fluid" src="{%static 'website/disaster_photo.jpeg'%}" alt="Earthquake image"/>
        </div>
    </div>
</section>

<!-- Boxes -->
<div class="section p-5">
    <div class="container">
        <div class="row text-centre">
            <div class="col-md">
                <div class="cards bg-dark text-light">
                    <div class="card-body text-centre">
                        <h3 class="card-title mb-3">Guidlines</h3>
                        <p class="card-text">Click here to know general measures!!!</p>
                        <a href="{% url 'dm:gen_guidelines' %}" class="href-">Read More...</a>
                    </div>
                </div>
            </div>
            <div class="col-md"></div>
            <div class="col-md"></div>
        </div>
    </div>
</div>
{% endblock %}

disasterMangement/website/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'dm:home' %}"> Disaster Mangement</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'dm:signup' %}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dm:signin' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dm:logout'%}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

disasterMangement/website/templates/signin.html
{% extends 'base.html'%}
{% block title %}Login Page{%endblock%}

{% block content %}
<div class="container">
    <br/>
    <h2 class="text-centre mb-4">Login Page</h2>
</div>
<form action="{% url 'dm:signin' %}" id="loginForm" method="POST">
    {% csrf_token %}
    <div class="col-md-6 offset-md-3">
        {{ form.as_p }}
    <br>
    <button type="submit" class="btn btn-primary">Login</button>
    </div>
</form>
{%endblock%}

disasterMangement/website/templates/signup.html
{% extends 'base.html'%}

{% block title %} Sign up! {% endblock %}

{% block content %}

<div class="col-md-6 offset-md-3">
  <h1>New User??? Create an account for free!!</h1>
  <h2>Sign up as:</h2>
  <a href="{% url 'dm:signup_vol' %}">Volunteer</a>
  <br>
  <a href="{% url 'dm:signup_org' %}">Organization</a>
</div>

{% endblock %}

disasterMangement/website/templates/signup_org.html
{% extends 'base.html' %}

{% block title %} Sign up!! {% endblock %}

{% block content %}
<form action="{% url 'dm:signup_org' %}" method="post" class="row g-3">
  {% csrf_token %}
  <div class="col-md-6 offset-md-3">
    {{ form.as_p }}

    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
      {% endfor %}
    {% endif %}
    
    <button type="submit" class="btn btn-primary">Sign up</button>
  </div>
</form>
{%endblock%}

disasterMangement/website/templates/signup_vol.html
{% extends 'base.html' %}

{% block title %} Sign up!! {% endblock %}

{% block content %}
<form action="{% url 'dm:signup_vol' %}" method="POST" class="row g-3">
  {% csrf_token %}
  <div class="col-md-6 offset-md-3">
    {{ form.as_p }}

    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
      {% endfor %}
    {% endif %}
    
    <button type="submit" class="btn btn-primary">Sign up</button>
  </div>
</form>
{%endblock%}

{%block script%}
{%endblock%}